# _config.yml
#
author: © 2017 Jεan Sacren
title: Scalable Vector Graphics
description: > # newline ignored in the block
  Graphics but
  not from
  drawing.
baseurl: /svg
url: https://sacren.github.io/svg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
